### ISSUE TITLE
CaptureTheFlag.sol example should implement IKnowForwarderAddress.sol

### ISSUE THREAD

**Issue by vrde** [qbzzt/opengsn#5]
If I try to relay a call to the `CaptureTheFlag` contract I get:

> Error: Rejected relayTransaction call - should not happen. Reason: Error: No forwarder address configured and no getTrustedForwarder in target contract (fetching from recipient failed)

After some digging I've discovered that `CaptureTheFlag` should implement `@opengsn/gsn/contracts/interfaces/IKnowForwarderAddress.sol` and override `getTrustedForwarder()`.

```solidity
pragma solidity ^0.6.2;
import "@opengsn/gsn/contracts/BaseRelayRecipient.sol";
import "@opengsn/gsn/contracts/interfaces/IKnowForwarderAddress.sol";

contract CaptureTheFlag is BaseRelayRecipient, IKnowForwarderAddress {
	event FlagCaptured(address _from, address _to);
	address flagHolder = address(0);

	constructor(address _forwarder) public {
		trustedForwarder = _forwarder;
	}

	function captureFlag() external {
		address previous = flagHolder;
		flagHolder = _msgSender();
		emit FlagCaptured(previous, flagHolder);
	}

	function versionRecipient() external view override returns (string memory) {
		return "0.0.1";
	}

	function getTrustedForwarder() public override view returns(address) {
		return trustedForwarder;
	}
}
```

This is also the approach of this test:

- https://github.com/opengsn/gsn/blob/678245937496b65d0d8a1b73cf3b92df276bfe6e/contracts/test/TestRecipient.sol

**Comment by qbzzt** [comment]
Thank you, I put in your changes. Now I just need to get a few more details and I'll be able to update the tutorial to match.
